### ISSUE TITLE
Configuration questions

### ISSUE THREAD

**Issue by jannavarro** [danielzen/material-todo#1]
Hi,

This isn't more of an issue but some clarifications on the configurations. I was following your tutorial [here](http://www.creativebloq.com/how-to/build-a-material-design-app-with-angular-2) which is still using your old repo material-2do.

In this new repo I noticed you do not have the angular-cli-build.js, and systemjs anymore. Another change is in your package.json you are using "@angular/material": "^2.0.0-alpha.9-3" which is an angular material using [angular 1](https://github.com/angular/material). Since I am new to web development these changes got me a little confused when checking your tutorial. I am running into an error in my app which is: 
`Value: Error: Error: XHR error (404 Not Found) loading http://localhost:4200/vendor/@angular/material(…) null`

When I created an app using angular cli I installer @angular/material. In my angular-cli-build.js I added material in the last line:

```
module.exports = function(defaults) {
  return new Angular2App(defaults, {
    vendorNpmFiles: [
      'systemjs/dist/system-polyfills.js',
      'systemjs/dist/system.src.js',
      'zone.js/dist/*.js',
      'es6-shim/es6-shim.js',
      'reflect-metadata/*.js',
      'rxjs/**/*.js',
      '@angular/**/*.js',
      **'@angular/material/*.js'**
    ]
  });
```

Then in system.config.ts:

```
const map: any = {
  '@angular/material': 'vendor/@angular/material'
};
```

I tried other approaches as well in modifying system.config.ts and angular-cli-build.js but still got the error. Your thoughts are much appreciated.

**Comment by danielzen** [comment]
Hello jannavoro,
  The old material-2do uses  a beta version of angular2 with a CLI that uses SystemJS , while this newer repo uses the final version of Angular2 with the CLI that relies on WebPack instead of SystemJS, and has no more systemjs nor angular-cli-build.js. In addition, the material repo has moved to @angular/material. In no case are we using Angular1.

I have yet to create a tutorial for the final version of Angular2, only this repo which shows the final product....
